/**
 * Schemas for the hand-written files in /content. These are the formats you
 * edit; normalize.ts turns them into the runtime model in types.ts.
 *
 * Objects are strict, so a misspelled field name is reported as an error
 * instead of being silently ignored.
 */
import { z } from "zod";

const id = z
  .string()
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "use lowercase letters, numbers and dashes");

const text = z.string().trim().min(1);

export const localizedSchema = z.strictObject({ en: text, es: text.optional() });

// ─── Categories ───────────────────────────────────────────────────────────

export interface CategoryInput {
  id: string;
  name: z.infer<typeof localizedSchema>;
  description?: z.infer<typeof localizedSchema>;
  children?: CategoryInput[];
}

export const categoryInputSchema: z.ZodType<CategoryInput> = z.lazy(() =>
  z.strictObject({
    id,
    name: localizedSchema,
    description: localizedSchema.optional(),
    children: z.array(categoryInputSchema).optional(),
  }),
);

export const categoriesFileSchema = z.array(categoryInputSchema);

// ─── Brands ───────────────────────────────────────────────────────────────

export const brandsFileSchema = z.array(
  z.strictObject({
    id,
    name: text,
    description: localizedSchema.optional(),
  }),
);

// ─── Option libraries (content/options/<option>.yaml) ─────────────────────

const optionCode = z.string().regex(/^[A-Z0-9]+$/, "use uppercase letters and numbers, e.g. NVY");

export const optionValueSchema = z.strictObject({
  id,
  code: optionCode,
  label: localizedSchema,
  hex: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/, 'use a 6-digit hex color like "#1f2a44"')
    .optional(),
});

export const optionLibrarySchema = z.strictObject({
  name: localizedSchema,
  type: z.enum(["swatch", "pill"]),
  values: z.array(optionValueSchema).min(1),
});

// ─── Products (content/products/<slug>.yaml) ──────────────────────────────

/** A product option: a list of value ids from a library, or an inline option. */
const productOptionSchema = z.union([
  z.array(id).min(1),
  z.strictObject({
    name: localizedSchema,
    type: z.enum(["swatch", "pill"]).default("pill"),
    values: z.array(optionValueSchema).min(1),
  }),
]);

const isoDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "use YYYY-MM-DD")
  .or(z.date().transform((d) => d.toISOString().slice(0, 10)));

export const productFileSchema = z.strictObject({
  id: z.string().regex(/^p_[0-9]{4,}$/, 'use "p_" followed by digits, e.g. p_0001'),
  slug: id,
  status: z.enum(["active", "draft", "archived"]),
  brand: id.optional(),
  categories: z.array(z.string().min(1)).min(1),
  name: localizedSchema,
  shortDescription: localizedSchema.optional(),
  description: localizedSchema,
  skuPrefix: z.string().regex(/^[A-Z0-9]+(?:-[A-Z0-9]+)*$/, "use uppercase, e.g. BED-CMF7"),
  /** Key order = display order. Library options: color, size, …; or inline. */
  options: z.record(id, productOptionSchema).optional(),
  /** Exceptions only; every option combination is generated automatically. */
  variants: z
    .array(
      z.strictObject({
        match: z.record(id, id),
        available: z.boolean().optional(),
        sku: z.string().min(1).optional(),
        barcode: z.string().min(1).optional(),
      }),
    )
    .optional(),
  packaging: z
    .strictObject({
      unit: z.enum(["piece", "pack", "case", "set", "dozen"]),
      unitsPerPack: z.int().positive().optional(),
      quantityStep: z.int().positive().optional(),
      minQuantity: z.int().positive().optional(),
    })
    .optional(),
  attributes: z
    .array(z.strictObject({ label: localizedSchema, value: localizedSchema }))
    .optional(),
  tags: z.array(id).optional(),
  featured: z.boolean().optional(),
  seo: z
    .strictObject({ title: localizedSchema.optional(), description: localizedSchema.optional() })
    .optional(),
  /** Alt text overrides keyed by photo file name without extension. */
  imageAlt: z.record(z.string(), localizedSchema).optional(),
  createdAt: isoDate,
  updatedAt: isoDate.optional(),
});

export type ProductFile = z.infer<typeof productFileSchema>;
export type OptionLibrary = z.infer<typeof optionLibrarySchema>;
export type BrandsFile = z.infer<typeof brandsFileSchema>;
export type CategoriesFile = z.infer<typeof categoriesFileSchema>;

// ─── Image manifest (generated by `npm run images:sync`) ──────────────────

export const imageManifestSchema = z.strictObject({
  version: z.literal(1),
  /** Keyed by product slug (= photo folder name). */
  products: z.record(
    z.string(),
    z.array(
      z.strictObject({
        file: z.string(), // original file name, e.g. "navy-1.jpg"
        hash: z.string(),
        src: z.string(),
        width: z.int().positive(),
        height: z.int().positive(),
        blurDataURL: z.string().optional(),
        provider: z.enum(["local", "cloudinary"]),
      }),
    ),
  ),
});

export type ImageManifest = z.infer<typeof imageManifestSchema>;
export type ManifestImage = ImageManifest["products"][string][number];
